### ISSUE TITLE
Updates return 

### ISSUE THREAD

**Issue by Matrix-sudo** [j-hc/mindetach-magisk#5]
Hey,
So I tried this module to detach - for starters or works, but at some point the updates return.
I'm running on a12, galaxy s20 fe 5g.

**Comment by j-hc** [comment]
there is a new version being tested on the telegram channel. you might want to try it.
https://t.me/rvc_magisk/47

**Comment by LtPatterson** [comment]
yep, same here P7 A13

**Comment by RomRider** [comment]
Same here, Pixel 7 pro

**Comment by red0fireus** [comment]
can't even get it to work on the Pixel 7 Pro

**Comment by sqylogin** [comment]
I have three devices that this is installed on. On two of the devices, YouTube is not popping up as an update. But in one device, it is. The two devices were running on Pixel-like custom Android 12 ROMs, while the device that's having an issue is running stock Android 13.

**Comment by bradtaylor9** [comment]
Updates on YouTube return. Pixel 6 a13 Feb update

**Comment by j-hc** [comment]
try v3
https://github.com/j-hc/mindetach-magisk/releases/tag/20230212

**Comment by blackwind** [comment]
Issue persists with v3.

**Comment by sqylogin** [comment]
> try v3 https://github.com/j-hc/mindetach-magisk/releases/tag/20230212

My issue is solved.

At some point, the default blocking of YouTube disappeared and mindetach was blocking nothing. I upgraded to version 3, and also dropped detach.txt into /sdcard. YouTube is now detached for me.

**Comment by j-hc** [comment]
> Issue persists with v3.

@blackwind join telegram for testing https://t.me/rv_magisk

**Comment by RomRider** [comment]
With v3, YouTube still appears as an update sometimes, but it also removes updates for quite a lot of other apps (eg. Gmail, Google,...)even if detach.txt only contains `com.google.android.youtube`.

Symptoms are:
* display the list of apps to be updated
* wait for several seconds
* most of the Google apps disappear from the list
* get to each individual app and they can be updated

**Comment by j-hc** [comment]
@RomRider join telegram for debugging
https://t.me/rv_magisk
